### ISSUE TITLE
Handling session

### ISSUE THREAD

**Issue by yanissoalili** [Faustharus/gallery#2]
hi Damien, 
login and the signup page are great, just one issue : 
After each hot restart, we must sign in another time.

**Comment by Faustharus** [comment]
I'll look into it

**Comment by Faustharus** [comment]
Bug fixed

**Comment by Faustharus** [comment]
Hi @yanissoalili ,
I'm currently about to the Graphic Integration of the app, hovewer while i'm doing it despite my attempt, i can't figure out where to put the SingleChildScrollView, i put it instead of the Stack but it doesn't work - I have this instead...
![Simulator Screen Shot - iPhone 13 - 2022-02-03 at 15 04 26](https://user-images.githubusercontent.com/48592115/152358667-a2939ef6-57c1-4276-b543-3b370c3624a3.png)

**Comment by yanissoalili** [comment]
Hi Damien, 
AdobeXd flutter Plugin generate always stack over stack😁

**Comment by Faustharus** [comment]
Hi Yanis :) - How are you ?
I have an issue ; I can't figure out why my bottom tab bar doesn't appear on my live screen(photo gallery)
